config/routes.rb
Piupiu::Application.routes.draw do
  root :to => "high_voltage/pages#show", :id => "index"

  devise_for :users, :controllers => { :registrations => "registrations", :passwords => "passwords", :sessions => "sessions" } do
    delete "users/:id" => "registrations#destroy"
    get "users/sign_up" => "registrations#new"
    get "users" => "users#index", :as => :user_root
    get "users/sign_in" => redirect("/")
  end

  resources :users do
      post "attachement_upload" => "users#attachement_upload"
  end

  resources :posts do
    get "comment" => "posts#comment"
    get "download" => "posts#download"
    post "report" => "posts#report"
  end
end

app/views/pages/check_mail.html.haml
.check_mail_container
  %img{ :src => "/images/check_mails-16.png" }

app/views/pages/delete_profile.html.haml
= form_for(:user, :as => :user, :url => "/users?id=#{current_user.id}", :html => { :method => :delete, :class => "text" }) do |f|
  = f.submit "", :class => "thumb_up"
  = link_to "", user_root_path, :class => "thumb_down"

= image_tag "delete_profile_illu-13.png", :class => "delete_profile_illu"

app/views/pages/impressum.html.haml
.text2
  %h1 the people behind piu piu
  %br
  %br
  = "Three austrian students had an idea. They got passionate about it and became piu-people with all their heart."
  %br
  %br
  = "piu people are:"
  %br
  = "Magdalena Achleitner (concept, design, illustrations)"
  %br
  = "Sonja Stangl (idea, concept, design, illustrations)"
  %br
  = "Ismail Hanli (coding)"
  %br
  %br
  %br
  = "special thanks to:"
  %br
  = "Manuel Eisl (processing)"
  %br
  = "Barbara Huber (coding version 1.0)"
  %br
  = "Vladimir Verivélle (inspiration)"
  %br
  = "chocolate & ice cream (sacrificial cooperation)"
  %br
  %br
  %br
  = "contact:"
  %br
  = "Sonja Stangl"
  %br
  = link_to "mimimi@piupiu.at", "mailto:mimimi@piupiu.at", :class => "piupiu_link"
  = image_tag "impressum_illu-18.png", :class => "illus"
.text2
  %h1#terms-of-use Terms of use
  %h2 Liability for Content
  = "We make every effort to keep the information on our Web site current, but accept no liability whatsoever for the content provided. Pursuant to §7 par. 1 of TMG (German Tele-Media Act), the law limits our responsibility as a service provider to our own content on these Web pages.  According to §§8 to 10 of TMG, we are not obligated to monitor third party information provided or stored on our Web site. However, we shall promptly remove any content upon becoming aware that it violates the law. Our liability in such an instance shall commence at the time we become aware of the respective violation."
  %h2 Copyrights
  = "The content and works provided on these Web pages are governed by the copyright laws of Germany. Duplication, processing, distribution, or any form of commercialization of such material beyond the scope of the copyright law shall require the prior written consent of its respective author or creator."
  %h2 Data Protection
  = "Please be aware that there are inherent security risks in transmitting data, such as e-mails, via the Internet, because it is impossible to safeguard completely against unauthorized access by third parties. Nevertheless, we shall safeguard your data, subject to this limitation. In particular, personal information will be transmitted via the Internet only if it does not infringe upon third-party rights, unless the respective party has given its prior consent in view of such security risks.  Accordingly, as the Web site provider, we shall not be held liable for any damages incurred as a consequence of such security risks or for any related acts of omission on our part.We oppose the use of any available contact information by a third party for sending unsolicited advertisements. As the Web site provider, we reserve the express right to take legal action against unsolicited mailing or e-mailing of spam and other similar advertising materials.   Source: "
  = link_to "Rechtsanwälte Streifler & Kollegen", "http://www.streifler.de", :class => "piupiu_link"
  = ";"
  = link_to "twigg’s Übersetzungsbüro", "http://www.uebersetzungdeutschenglisch.com", :class => "piupiu_link"
  %br
  %br
  %br

app/views/pages/index.html.haml
.start_container
  = link_to "", page_path("wtf"), :class => "start_wtf"
  = link_to "", new_user_registration_path, :class => "start_signup"
  
  - if flash[:alert] == I18n.t("devise.failure.invalid")
    = image_tag "pw_falsch-17.png", :class => "pw_wrong"
  - else
    = flash[:alert]
    
  .login
    = link_to "", user_root_path, :class => "start_login"
    
    = form_for(:user, :as => :user, :url => user_session_path, :html => { :class => "login_feld" }) do |f|
      = f.text_field :email, :size => "18", :class => "feld"
      = f.password_field :password, :size => "18", :class => "feld"
      = f.submit "", :class => "check"
      = link_to "", new_user_password_path, :class => "forgot_pw"

app/views/pages/profile_deleted.html.haml
.fehler_pic_02
  %img{ :src => "/images/profile_deleted-19.png" }

app/views/pages/signin.html.haml
.fehler_pic_02
  %a{ :href => root_path }
    %img{ :src => "/images/need_to_sign_in-19.png" }

app/views/pages/timeout.html.erb
<div class="fehler_pic_02">
<%= link_to image_tag("need_to_sign_in-19.png"), root_path %>
</div>

app/views/pages/wtf.html.haml
.text2
  %h1 wtf?
  %br
  %br
  = "What is piu piu? First of all, this is one of the few pages containing letters you'll find here. The thing is, that we are trying to get people to communicate without words on this website and we'd love to see you express yourself in a different way. For starting at ourselves first, we set a good example by using only icons for navigation on the website."
  %br
  %br
  = "How it all started: One day we thought, that the world could be a better place...and because we are only secretly super heroes, we had to find an inconspicuous way to get rid of some grievous ills. Our first goal is to decrease the amount of empty words, by creating this website ;)"
  %br
  %br
  = "You may still ask yourself \"what the fuck?\" We live in a world where we are swamped with information from various sources. The relevance of these messages is mostly questionable. Especially on social media platforms the spread of word vomit is carried to extremes. This causes the feeling that some people write faster than they think. To counteract this we hope to slow down the process of developing messages by getting you to create them without words."
  %br
  %br
  = "If you still ask yourself \"what the fuck?\"...just try it!"
  %br
  %br
  = "Should you not be able to figure out everything, or you have other questions, or you just want to say hi, contact us on "
  = link_to "mimimi@piupiu.at", "mailto:mimimi@piupiu.at", :class => "piupiu_link"
  = image_tag "wtf_illu-18.png", :class => "illus"